<a href="https://colab.research.google.com/github/MENDEMUKESH/1MLproject/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4]),
print(a)

(array([1, 2, 3, 4]),)


In [7]:
b=np.array([[1,2,3],[3,4,5]]),
print(b)

(array([[1, 2, 3],
       [3, 4, 5]]),)


In [15]:
c=np.array([
    [[1,2,3],[3,4,5]],
    [[6,4,5],[7,8,9]],


])
print(c)

[[[1 2 3]
  [3 4 5]]

 [[6 4 5]
  [7 8 9]]]


In [17]:
print(c[0][1][0])

3


In [20]:
d= np.array([

             [[1,2,3],[3,4,5]],
             [[7,8,9],[5,6,7]],
])

np.asarray(d,dtype=float,order='C')
print (d)

[[[1 2 3]
  [3 4 5]]

 [[7 8 9]
  [5 6 7]]]


In [28]:
for i in np.nditer(d):
  print(i)                         # nditer to iterate the loop

1
2
3
3
4
5
7
8
9
5
6
7


In [37]:
e = b"hello india"
f=np.frombuffer(e,dtype="S1",count =2)
print(f)

[b'h' b'e']


In [38]:
 g=np.random.rand(1,2)
 print(g)                             # np.zeros(),np.full(),np.ones()

[[0.57256809 0.12862925]]


In [39]:
a= np.eye(3,3)                        #identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
a = np.array([1,2,3,4,5,6])
a.reshape(2,3)

print(b)


(array([[1, 2, 3],
       [3, 4, 5]]),)


In [44]:
a = np.arange(10,100,5)
print (a)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [50]:
#slicing

print(a[0:5])                  #doesnt print value of last like 5,6
print(a[:6])
print(a[7:])



[10 15 20 25 30]
[10 15 20 25 30 35]
[45 50 55 60 65 70 75 80 85 90 95]


In [61]:
da = np.dtype([('name','S1'),('perc','float')])

data = np.array([('mukesh','93'),('sneugu','99')],dtype=da,)

np.sort(data,order='perc')

print (data)

[(b'm', 93.) (b's', 99.)]


In [62]:
import pandas as pd


In [ ]:
data = pd.read_csv("file name")

data

In [69]:
df ={

     'Name':['ran','den','mun'],
     'class':[1,2,3],
     'age':[20,30,40]
}

In [70]:
df

{'Name': ['ran', 'den', 'mun'], 'class': [1, 2, 3], 'age': [20, 30, 40]}

In [72]:
dt=pd.DataFrame(df)
dt

Name  class  age
0  ran      1   20
1  den      2   30
2  mun      3   40

In [73]:
dt.info()
dt.head()
dt.tail()
dt.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   class   3 non-null      int64 
 2   age     3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


class   age
count    3.0   3.0
mean     2.0  30.0
std      1.0  10.0
min      1.0  20.0
25%      1.5  25.0
50%      2.0  30.0
75%      2.5  35.0
max      3.0  40.0

In [ ]:
dt.[]