In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [2]:
df=pd.read_csv('hiring.csv')

In [3]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
df.rename({'test_score(out of 10)':'test_score','interview_score(out of 10)':'interview_score'},axis=1,inplace=True)

In [36]:
df


experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         7.0                7      72000
7          11         7.0                8      80000

In [6]:
df.experience.fillna('zero',inplace=True)

In [7]:

!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5566 sha256=008eccd8c852d121670038c72b55eb0317ab59f2bb5c56e5be3bfb2d1f1e6388
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [8]:
import math
mean=math.floor(df.test_score.mean())
mean

7

In [9]:
df.test_score.fillna(mean,inplace=True)

In [10]:
df


experience  test_score  interview_score  salary($)
0       zero         8.0                9      50000
1       zero         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         7.0                7      72000
7     eleven         7.0                8      80000

In [11]:
from word2number import w2n


In [12]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         7.0                7      72000
7          11         7.0                8      80000

In [13]:
df.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [28]:
reg=linear_model.LinearRegression()
X=df[['experience','test_score','interview_score']]
y=df['salary($)']
reg.fit(X,y)

LinearRegression()

AttributeError: 'DataFrame' object has no attribute 'coeff'

In [29]:
reg.predict([[1,2,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([28799.98635999])

In [16]:
!pip install scikit-learn

In [17]:
import joblib

In [18]:
joblib.dump(reg,'hiring.pkl')

['hiring.pkl']

In [19]:
joblib.load('hiring.pkl')

LinearRegression()

In [30]:
reg.score(X,y)

0.9770139014273139

In [40]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [44]:
reg.predict([[0,7,7]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([45574.19310839])

In [45]:
reg.predict([[0,3,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([28099.02644456])